apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-feed
  template:
    spec:
      containers:
        - name: microservice-container
          image: your-registry/your-microservice-image:tag
          # ... other container configurations ...
          env:
            - name: AWS_REGION
              value: your_s3_bucket_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
