apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Add any additional permissions needed for your microservice
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: microservice-role
subjects:
  - kind: ServiceAccount
    name: default # Update this if your microservice uses a specific service account
    namespace: default # Update this if your microservice is deployed in a different namespace
