version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-frontend w024sec/udagram-frontend:v1
            docker tag udagram-api-feed w024sec/udagram-api-feed:v1
            docker tag udagram-api-user w024sec/udagram-api-user:v1
            docker tag udagram-reverseproxy w024sec/reverseproxy:v1
            docker push udagram-frontend w024sec/udagram-frontend:v1
            docker push udagram-api-feed w024sec/udagram-api-feed:v1
            docker push udagram-api-user w024sec/udagram-api-user:v1
            docker push udagram-reverseproxy w024sec/reverseproxy:v1

workflows:
  version: 2.1
  build-and-push:
    jobs:
      - build
